[package]
name = "ectool"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Generic command-line tools for EigenComm cellular chips"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
crc32fast = "1"
env_logger = "0.11"
hex = "0.4"
indicatif = "0.17"
log = "0.4"
regex = "1"
serialport = { version = "4", features = ["usbportinfo-interface"] }
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
